//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

// An System.Collections.ObjectModel.ObservableCollection that raises
// individual item removal notifications on clear and prevents adding duplicates.
public class FixupCollection<T> : ObservableCollection<T>
{
    protected override void ClearItems()
    {
        new List<T>(this).ForEach(t => Remove(t));
    }

    protected override void InsertItem(int index, T item)
    {
        if (!this.Contains(item))
        {
            base.InsertItem(index, item);
        }
    }
}
public partial class ict_Course
{
    #region Primitive Properties

    public virtual int courseID
    {
        get;
        set;
    }

    public virtual string courseName
    {
        get;
        set;
    }

    public virtual string courseCode
    {
        get;
        set;
    }

    public virtual string courseDescription
    {
        get;
        set;
    }

    #endregion
}
public partial class ict_Degree
{
    #region Primitive Properties

    public virtual int degreeID
    {
        get;
        set;
    }

    public virtual string degreeName
    {
        get;
        set;
    }

    public virtual string degreeDuration
    {
        get;
        set;
    }

    public virtual string degreeDescription
    {
        get;
        set;
    }

    public virtual string degreeCode
    {
        get;
        set;
    }

    #endregion
}
public partial class ict_DegreeCourse
{
    #region Primitive Properties

    public virtual int Id
    {
        get;
        set;
    }

    public virtual string Code
    {
        get;
        set;
    }

    public virtual string Name
    {
        get;
        set;
    }

    public virtual string URLOutline
    {
        get;
        set;
    }

    #endregion
}
public partial class ict_Diploma
{
    #region Primitive Properties

    public virtual int diplomaID
    {
        get;
        set;
    }

    public virtual string diplomaName
    {
        get;
        set;
    }

    public virtual string diplomaDuration
    {
        get;
        set;
    }

    public virtual string diplomaDescription
    {
        get;
        set;
    }

    public virtual string diplomaCode
    {
        get;
        set;
    }

    #endregion
}
public partial class ict_DiplomaCourse
{
    #region Primitive Properties

    public virtual int Id
    {
        get;
        set;
    }

    public virtual string Code
    {
        get;
        set;
    }

    public virtual string Name
    {
        get;
        set;
    }

    public virtual string URLOutline
    {
        get;
        set;
    }

    #endregion
}
public partial class ict_Feedback
{
    #region Primitive Properties

    public virtual int feedbackID
    {
        get;
        set;
    }

    public virtual string feedback
    {
        get;
        set;
    }

    public virtual System.DateTime date
    {
        get;
        set;
    }

    #endregion
}
public partial class ict_Graduate
{
    #region Primitive Properties

    public virtual int graduateID
    {
        get;
        set;
    }

    public virtual string graduateName
    {
        get;
        set;
    }

    public virtual string graduateDuration
    {
        get;
        set;
    }

    public virtual string graduateDescription
    {
        get;
        set;
    }

    public virtual string graduateCode
    {
        get;
        set;
    }

    #endregion
}
public partial class ict_GraduateCourse
{
    #region Primitive Properties

    public virtual int Id
    {
        get;
        set;
    }

    public virtual string Code
    {
        get;
        set;
    }

    public virtual string Name
    {
        get;
        set;
    }

    public virtual string URLOutline
    {
        get;
        set;
    }

    #endregion
}
public partial class ict_Job
{
    #region Primitive Properties

    public virtual int jobID
    {
        get;
        set;
    }

    public virtual string jobDescription
    {
        get;
        set;
    }

    #endregion
}
public partial class ict_Page
{
    #region Primitive Properties

    public virtual int PageID
    {
        get;
        set;
    }

    public virtual string Content
    {
        get;
        set;
    }

    public virtual string Title
    {
        get;
        set;
    }

    public virtual Nullable<System.DateTime> DateCreated
    {
        get;
        set;
    }

    public virtual Nullable<System.DateTime> DateModified
    {
        get;
        set;
    }

    #endregion
}
public partial class ict_Program
{
    #region Primitive Properties

    public virtual int programID
    {
        get;
        set;
    }

    public virtual string porgramName
    {
        get;
        set;
    }

    public virtual string programCode
    {
        get;
        set;
    }

    public virtual string programType
    {
        get;
        set;
    }

    public virtual string programDuration
    {
        get;
        set;
    }

    #endregion
}
public partial class ict_ProgramOverview
{
    #region Primitive Properties

    public virtual int Id
    {
        get;
        set;
    }

    public virtual string ProgramName
    {
        get;
        set;
    }

    public virtual string ProgramCode
    {
        get;
        set;
    }

    public virtual string ProgramDescription
    {
        get;
        set;
    }

    public virtual string ProgramDuration
    {
        get;
        set;
    }

    public virtual string ProgramCredential
    {
        get;
        set;
    }

    #endregion
}
public partial class ict_Staff
{
    #region Primitive Properties

    public virtual int staffID
    {
        get;
        set;
    }

    public virtual string firstName
    {
        get;
        set;
    }

    public virtual string lastName
    {
        get;
        set;
    }

    public virtual string responsibility
    {
        get;
        set;
    }

    public virtual string email
    {
        get;
        set;
    }

    public virtual string extention
    {
        get;
        set;
    }

    public virtual string office
    {
        get;
        set;
    }

    public virtual string website
    {
        get;
        set;
    }

    #endregion
}
public partial class ict_Student
{
    #region Primitive Properties

    public virtual int studentID
    {
        get;
        set;
    }

    public virtual string firstName
    {
        get;
        set;
    }

    public virtual string lastName
    {
        get;
        set;
    }

    public virtual string programName
    {
        get;
        set;
    }

    public virtual string semester
    {
        get;
        set;
    }

    public virtual string email
    {
        get;
        set;
    }

    #endregion
}
